print("Escribe tu numero (a): ")
num1 = input()
num2 = input("Escribe tu otro numero (b): ")
#Operaciones Matemáticas
suma = float(num1) + float(num2)
resta1 = float(num1) - float(num2)
resta2 = float(num2) - float(num1)
multiplicacion = float(num1) * float(num2)
division1 = float(num1) / float(num2)
division2 = float(num2) / float(num1)
potencia1 = float(num1)**float(num2)
potencia2 = pow(float(num2),float(num1))
residuo1 = float(num1)%float(num2)
residuo2 = float(num2)%float(num1)
raizcuada = pow(float(num1),float(1/2))
raizcuadb = pow(float(num2),float(1/2))
raizcuba = pow(float(num1),float(1/3))
raizcubb = pow(float(num2),float(1/3))
print("La suma es: " + str(suma))
print("La resta (1~a-b) es: " + str(resta1))
print("La resta (2~b-a) es: " + str(resta2))
print("La multiplicación es: " + str(multiplicacion))
print("La división (1~a/b) es: " + str(division1))
print("La división (2~b/a) es: " + str(division2))
print("La potencia (1~a^b) es: " + str(potencia1))
print("La potencia (2~b^a) es: " + str(potencia2))
print("El residuo (1) es: " + str(residuo1))
print("El residuo (2) es: " + str(residuo2))
print("La raíz cuadrada de a es: " + str(raizcuada))
print("La raíz cuadrada de b es: " + str(raizcuada))
print("La raíz cúbica de a es: " + str(raizcuba))
print("La raíz cúbica de b es: " + str(raizcubb))
print(type(suma))
print(type(resta1))
print(type(resta2))
print(type(multiplicacion))
print(type(division1))
print(type(division2))
print(type(potencia1))
print(type(potencia2))
print(type(residuo1))
print(type(residuo2))
print(type(raizcuada))
print(type(raizcuadb))
print(type(raizcuba))
print(type(raizcubb))
