# Tipos de Datos
print("Escribe tu nombre:")
nombrePersona = input()
print("Escribe tu edad:")
edadPersona = input()
print("Escribe tu dirección:")
direccionPersona = input()
print("Escribe tu teléfono:")
telefonoPersona = input()
print("Escribe tu peso:")
pesoPersona = input()
print("¿Eres estudiante? ( True=Si / False=No )")
estudiante = input()
print("Nombre: " + nombrePersona + "\n" + "Edad: " + str(edadPersona) + "\n" + "Dirección: " + direccionPersona)
print("Teléfono: " + str(telefonoPersona) + "\n" + "Peso: " + str(pesoPersona) + "\n" + "Estudia: " + str(estudiante))
print("\n" + "\n")
print(type(nombrePersona))
print(type(edadPersona))
print(type(direccionPersona))
print(type(telefonoPersona))
print(type(pesoPersona))
print(type(estudiante))
